default: &default
  adapter: postgresql
  encoding: unicode
  username: postgresql
  password: 123456
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quiz_rails8_app_development

test:
  <<: *default
  database: quiz_rails8_app_test

production:
  primary: &primary_production
    <<: *default
    database: quiz_rails8_app_production
    username: quiz_rails8_app
    password: <%= ENV["QUIZ_RAILS8_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: quiz_rails8_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: quiz_rails8_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: quiz_rails8_app_production_cable
    migrations_paths: db/cable_migrate
